name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: cicirello/user-statistician@v1
        with:
          colors: dark-dimmed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
